export const environment = {
    production: false,
    jwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwiZW1haWwiOiJ3ZWJzZXJ2ZXJAZW1haWwuY29tIiwiaWF0IjoxNzM3MTM1Mzc0LCJleHAiOjM1MDMxMjIwNDg5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.XZ3KUvLJoQedQyUMS27ipQEgw2P0umdvSIHF8SzkbPE',
};
